name: Build & publish release
on: [push]
jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Publish to Registry
              uses: HurricanKai/Publish-Docker-Github-Action@master
              with:
                  name: wdaan/DiscordBot
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
